import Head from "next/head";

import { useState } from "react";

import homeMain from "../css/module/homeMain.module.css";

import Article from "../components/ArticleHome";
import { IntroHome } from "../components/IntroHome";
import { Portfolio } from "../components/Portfolio";
import { ArticlesLanguages } from "../components/ArticlesLanguages";

export default function Home({ data }) {
  const [ articleMostRecent, setArticleMostRecent ] = useState(true)

  const articlesMostViwed = data.sort((a, b) => b.visits - a.visits)

  let articlesOrderByCreatedAt__temp = []

  for(let item in data) {
    let itemTemp = data[item].createdAt
    
    let arr = itemTemp.split('')
    arr.splice(4, 1)
    arr.splice(6, 1)

    arr = Number(arr.join(''))

    articlesOrderByCreatedAt__temp.push({
      createdAt: arr,
      title: data[item].title,
      articles_url: data[item].articles_url,
      
    })
  }

  articlesOrderByCreatedAt__temp = articlesOrderByCreatedAt__temp.sort((a, b) => b.createdAt - a.createdAt)
  
  const articlesOrderByCreatedAt = []

  for(let item in articlesOrderByCreatedAt__temp) {

    const arr = articlesOrderByCreatedAt__temp[item].createdAt.toString().split('')
    arr.splice(4,0, '/')
    arr.splice(7, 0, '/')
    
    articlesOrderByCreatedAt.push({
      createdAt: arr.join(''),
      title: articlesOrderByCreatedAt__temp[item].title,
      articles_url: articlesOrderByCreatedAt__temp[item].articles_url,
    })
  }

  return (
    <>
      <Head>
        <title>Marcos Segantine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <IntroHome />

      <main className={homeMain.home__main}>
        <div className={homeMain.lineTop}></div>
        <div className={homeMain.home__main__filter}>
        </div>

          <div className={homeMain.home__main__articles__filter}>
            <span className={articleMostRecent ? homeMain.home__main__articles__filter__selected : ""} onClick={() => setArticleMostRecent(true)}>Mais recentes</span>
            <span className={!articleMostRecent ? homeMain.home__main__articles__filter__selected : ""} onClick={() => setArticleMostRecent(false)}>Mais vistos</span>
          </div>
        <div className={articleMostRecent ? `${homeMain["home__main__articles"]} ${homeMain["home__main__articles-animation--left_to_right"]}` : `${homeMain["home__main__articles"]} ${homeMain["home__main__articles-animation--right_to_left"]}`}>
          
        {
          articleMostRecent ?
          articlesOrderByCreatedAt.map(data => {
            return(
              <Article
                key={data.title}
                title={data.title}
                linkUrl={data.articles_url}
              />
            )
          }) : 
          articlesMostViwed.map(data => {
            return(
              <Article
                key={data.title}
                title={data.title}
                linkUrl={data.articles_url}
              />
            )
          })
        }

        </div>
        
        <ArticlesLanguages data={data} />
        <Portfolio />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch("https:www.segantine.dev/api/getDataToHome");
  const data = await res.json();

  return {
    props: {
      data,
    },
  };
}
