import Head from "next/head";

import { useState } from "react";

import homeMain from "../css/module/homeMain.module.css";

import Article from "../components/ArticleHome";
import { IntroHome } from "../components/IntroHome";
import { Portfolio } from "../components/Portfolio";
import { ArticlesLanguages } from "../components/ArticlesLanguages";

import { orderArtilcesByDate } from '../functions/orderArtilcesByDate'

export default function Home({ data }) {
  const [ articleMostRecent, setArticleMostRecent ] = useState(true)

  const articlesOrderByMostViwed = data.sort((a, b) => b.visits - a.visits)

  const articlesOrderByCreatedAt = orderArtilcesByDate(data)

  const classNameArticles = articleMostRecent ?
     `${homeMain["home__main__articles"]} ${homeMain["home__main__articles-animation--left_to_right"]}` :
     `${homeMain["home__main__articles"]} ${homeMain["home__main__articles-animation--right_to_left"]}`

  return (
    <>
      <Head>
        <title>Marcos Segantine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <IntroHome />

      <main className={homeMain.home__main}>
        <div className={homeMain.lineTop}></div>
        <div className={homeMain.home__main__filter}>
        </div>

          <div className={homeMain.home__main__articles__filter}>
            <span className={articleMostRecent ? homeMain.home__main__articles__filter__selected : ""} onClick={() => setArticleMostRecent(true)}>Mais recentes</span>
            <span className={!articleMostRecent ? homeMain.home__main__articles__filter__selected : ""} onClick={() => setArticleMostRecent(false)}>Mais vistos</span>
          </div>
        <div className={classNameArticles}>
          
        {
          articleMostRecent ?
          articlesOrderByCreatedAt.map(data => {
            return(
              <Article
                key={data.title}
                title={data.title}
                linkUrl={data.articles_url}
              />
            )
          }) : 
          articlesOrderByMostViwed.map(data => {
            return(
              <Article
                key={data.title}
                title={data.title}
                linkUrl={data.articles_url}
              />
            )
          })
        }
        
        </div>
        <ArticlesLanguages data={data} />
        <Portfolio />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch("https:www.segantine.dev/api/getDataToHome");
  const data = await res.json();

  return {
    props: {
      data,
    },
  };
}
